-- Database definition for the quarantine management demo
-- Designed for Oracle APEX
------------------------------------------------------------------------------
-- 1. System State
------------------------------------------------------------------------------

CREATE TABLE SYSTEM_STATUS (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STATUS      VARCHAR2(20) NOT NULL,             -- 'NORMAL' or 'PANDEMIC'
    UPDATED_AT  DATE DEFAULT SYSDATE,
    UPDATED_BY  VARCHAR2(50)
);

CREATE TABLE STATUS_HISTORY (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STATUS      VARCHAR2(20) NOT NULL,
    CHANGED_AT  DATE DEFAULT SYSDATE,
    CHANGED_BY  VARCHAR2(50) NOT NULL
);

------------------------------------------------------------------------------
-- 2. Entry Management
------------------------------------------------------------------------------

CREATE TABLE TRAVELERS (
    TRAVELER_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FULL_NAME      VARCHAR2(200) NOT NULL,
    PASSPORT_NO    VARCHAR2(50) NOT NULL,
    NATIONALITY    VARCHAR2(100),
    GENDER         VARCHAR2(10),
    BIRTH_DATE     DATE,
    ENTRY_DATE     DATE NOT NULL,
    FLIGHT_NO      VARCHAR2(20),
    ORIGIN         VARCHAR2(100),
    DESTINATION    VARCHAR2(100),
    NOTE           VARCHAR2(500),
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE
);

------------------------------------------------------------------------------
-- 3. Health Declarations
------------------------------------------------------------------------------

CREATE TABLE HEALTH_DECLARATIONS (
    DECLARATION_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRAVELER_ID       NUMBER NOT NULL,
    TEMPERATURE       NUMBER(5,2),
    SYMPTOMS          VARCHAR2(1000),
    CONTACT_HISTORY   VARCHAR2(1000),
    RISK_ZONES        VARCHAR2(1000),
    TEST_FILE         VARCHAR2(255),
    DECLARED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT FK_HEALTH_TRAVELER FOREIGN KEY (TRAVELER_ID)
        REFERENCES TRAVELERS(TRAVELER_ID)
);

------------------------------------------------------------------------------
-- 4. Testing Management
------------------------------------------------------------------------------

CREATE TABLE TEST_ORDERS (
    TEST_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRAVELER_ID   NUMBER NOT NULL,
    TEST_DATE     DATE NOT NULL,
    TEST_TYPE     VARCHAR2(50),
    RESULT        VARCHAR2(50),
    RESULT_DATE   DATE,
    ALERT_FLAG    VARCHAR2(1) DEFAULT 'N',
    CONSTRAINT FK_TEST_TRAVELER FOREIGN KEY (TRAVELER_ID)
        REFERENCES TRAVELERS(TRAVELER_ID)
);

------------------------------------------------------------------------------
-- 5. Activity Logs (optional)
------------------------------------------------------------------------------

CREATE TABLE ACTIVITY_LOGS (
    LOG_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ACTION        VARCHAR2(100) NOT NULL,
    PERFORMED_AT  DATE DEFAULT SYSDATE,
    PERFORMED_BY  VARCHAR2(50),
    DETAIL        VARCHAR2(1000)
);

